# indian_locations.py — Comprehensive Indian States and 600+ Districts Mapping
INDIAN_STATES = {
    "andaman and nicobar islands": "Andaman and Nicobar Islands",
    "andhra pradesh": "Andhra Pradesh",
    "arunachal pradesh": "Arunachal Pradesh",
    "assam": "Assam",
    "bihar": "Bihar",
    "chandigarh": "Chandigarh",
    "chhattisgarh": "Chhattisgarh",
    "dadra and nagar haveli and daman and diu": "Dadra and Nagar Haveli and Daman and Diu",
    "daman and diu": "Daman and Diu",
    "delhi": "Delhi",
    "goa": "Goa",
    "gujarat": "Gujarat",
    "haryana": "Haryana",
    "himachal pradesh": "Himachal Pradesh",
    "jammu and kashmir": "Jammu and Kashmir",
    "jharkhand": "Jharkhand",
    "karnataka": "Karnataka",
    "kerala": "Kerala",
    "ladakh": "Ladakh",
    "lakshadweep": "Lakshadweep",
    "madhya pradesh": "Madhya Pradesh",
    "maharashtra": "Maharashtra",
    "manipur": "Manipur",
    "meghalaya": "Meghalaya",
    "mizoram": "Mizoram",
    "nagaland": "Nagaland",
    "odisha": "Odisha",
    "orissa": "Odisha",
    "puducherry": "Puducherry",
    "pondicherry": "Puducherry",
    "punjab": "Punjab",
    "rajasthan": "Rajasthan",
    "sikkim": "Sikkim",
    "tamil nadu": "Tamil Nadu",
    "telangana": "Telangana",
    "tripura": "Tripura",
    "uttar pradesh": "Uttar Pradesh",
    "up": "Uttar Pradesh",
    "uttarakhand": "Uttarakhand",
    "uttaranchal": "Uttarakhand",
    "west bengal": "West Bengal",
    "bengal": "West Bengal",
}

# District name -> (Canonical District, Canonical State)
INDIAN_DISTRICTS = {
    # Punjab
    "amritsar": ("Amritsar", "Punjab"),
    "barnala": ("Barnala", "Punjab"),
    "bathinda": ("Bathinda", "Punjab"),
    "faridkot": ("Faridkot", "Punjab"),
    "fatehgarh sahib": ("Fatehgarh Sahib", "Punjab"),
    "fazilka": ("Fazilka", "Punjab"),
    "ferozepur": ("Ferozepur", "Punjab"),
    "gurdaspur": ("Gurdaspur", "Punjab"),
    "hoshiarpur": ("Hoshiarpur", "Punjab"),
    "jalandhar": ("Jalandhar", "Punjab"),
    "kapurthala": ("Kapurthala", "Punjab"),
    "ludhiana": ("Ludhiana", "Punjab"),
    "mansa": ("Mansa", "Punjab"),
    "moga": ("Moga", "Punjab"),
    "muktsar": ("Muktsar", "Punjab"),
    "sri muktsar sahib": ("Sri Muktsar Sahib", "Punjab"),
    "pathankot": ("Pathankot", "Punjab"),
    "patiala": ("Patiala", "Punjab"),
    "rupnagar": ("Rupnagar", "Punjab"),
    "ropar": ("Rupnagar", "Punjab"),
    "sahibzada ajit singh nagar": ("SAS Nagar", "Punjab"),
    "mohali": ("SAS Nagar", "Punjab"),
    "sangrur": ("Sangrur", "Punjab"),
    "shahid bhagat singh nagar": ("SBS Nagar", "Punjab"),
    "nawanshahr": ("SBS Nagar", "Punjab"),
    "tarn taran": ("Tarn Taran", "Punjab"),
    "malerkotla": ("Malerkotla", "Punjab"),

    # Haryana
    "ambala": ("Ambala", "Haryana"),
    "bhiwani": ("Bhiwani", "Haryana"),
    "charkhi dadri": ("Charkhi Dadri", "Haryana"),
    "faridabad": ("Faridabad", "Haryana"),
    "fatehabad": ("Fatehabad", "Haryana"),
    "gurugram": ("Gurugram", "Haryana"),
    "gurgaon": ("Gurugram", "Haryana"),
    "hisar": ("Hisar", "Haryana"),
    "jhajjar": ("Jhajjar", "Haryana"),
    "jind": ("Jind", "Haryana"),
    "kaithal": ("Kaithal", "Haryana"),
    "karnal": ("Karnal", "Haryana"),
    "kurukshetra": ("Kurukshetra", "Haryana"),
    "mahendragarh": ("Mahendragarh", "Haryana"),
    "narnaul": ("Mahendragarh", "Haryana"),
    "nuh": ("Nuh", "Haryana"),
    "mewat": ("Nuh", "Haryana"),
    "palwal": ("Palwal", "Haryana"),
    "panchkula": ("Panchkula", "Haryana"),
    "panipat": ("Panipat", "Haryana"),
    "rewari": ("Rewari", "Haryana"),
    "rohtak": ("Rohtak", "Haryana"),
    "sirsa": ("Sirsa", "Haryana"),
    "sonipat": ("Sonipat", "Haryana"),
    "yamunanagar": ("Yamunanagar", "Haryana"),

    # Uttar Pradesh
    "agra": ("Agra", "Uttar Pradesh"),
    "aligarh": ("Aligarh", "Uttar Pradesh"),
    "ambedkar nagar": ("Ambedkar Nagar", "Uttar Pradesh"),
    "amethi": ("Amethi", "Uttar Pradesh"),
    "amroha": ("Amroha", "Uttar Pradesh"),
    "auraiya": ("Auraiya", "Uttar Pradesh"),
    "ayodhya": ("Ayodhya", "Uttar Pradesh"),
    "faizabad": ("Ayodhya", "Uttar Pradesh"),
    "azamgarh": ("Azamgarh", "Uttar Pradesh"),
    "baghpat": ("Baghpat", "Uttar Pradesh"),
    "bahraich": ("Bahraich", "Uttar Pradesh"),
    "ballia": ("Ballia", "Uttar Pradesh"),
    "balrampur": ("Balrampur", "Uttar Pradesh"),
    "banda": ("Banda", "Uttar Pradesh"),
    "barabanki": ("Barabanki", "Uttar Pradesh"),
    "bareilly": ("Bareilly", "Uttar Pradesh"),
    "basti": ("Basti", "Uttar Pradesh"),
    "bhadohi": ("Bhadohi", "Uttar Pradesh"),
    "sant ravidas nagar": ("Bhadohi", "Uttar Pradesh"),
    "bijnor": ("Bijnor", "Uttar Pradesh"),
    "budaun": ("Budaun", "Uttar Pradesh"),
    "bulandshahr": ("Bulandshahr", "Uttar Pradesh"),
    "chandauli": ("Chandauli", "Uttar Pradesh"),
    "chitrakoot": ("Chitrakoot", "Uttar Pradesh"),
    "deoria": ("Deoria", "Uttar Pradesh"),
    "etah": ("Etah", "Uttar Pradesh"),
    "etawah": ("Etawah", "Uttar Pradesh"),
    "farrukhabad": ("Farrukhabad", "Uttar Pradesh"),
    "fatehpur": ("Fatehpur", "Uttar Pradesh"),
    "firozabad": ("Firozabad", "Uttar Pradesh"),
    "gautam buddha nagar": ("Gautam Buddha Nagar", "Uttar Pradesh"),
    "noida": ("Gautam Buddha Nagar", "Uttar Pradesh"),
    "greater noida": ("Gautam Buddha Nagar", "Uttar Pradesh"),
    "ghaziabad": ("Ghaziabad", "Uttar Pradesh"),
    "ghazipur": ("Ghazipur", "Uttar Pradesh"),
    "gonda": ("Gonda", "Uttar Pradesh"),
    "gorakhpur": ("Gorakhpur", "Uttar Pradesh"),
    "hamirpur": ("Hamirpur", "Uttar Pradesh"),
    "hapur": ("Hapur", "Uttar Pradesh"),
    "hardoi": ("Hardoi", "Uttar Pradesh"),
    "hathras": ("Hathras", "Uttar Pradesh"),
    "jalaun": ("Jalaun", "Uttar Pradesh"),
    "jaunpur": ("Jaunpur", "Uttar Pradesh"),
    "jhansi": ("Jhansi", "Uttar Pradesh"),
    "kannauj": ("Kannauj", "Uttar Pradesh"),
    "kanpur dehat": ("Kanpur Dehat", "Uttar Pradesh"),
    "kanpur nagar": ("Kanpur Nagar", "Uttar Pradesh"),
    "kanpur": ("Kanpur Nagar", "Uttar Pradesh"),
    "kasganj": ("Kasganj", "Uttar Pradesh"),
    "kaushambi": ("Kaushambi", "Uttar Pradesh"),
    "kheri": ("Lakhimpur Kheri", "Uttar Pradesh"),
    "lakhimpur": ("Lakhimpur Kheri", "Uttar Pradesh"),
    "kushinagar": ("Kushinagar", "Uttar Pradesh"),
    "lalitpur": ("Lalitpur", "Uttar Pradesh"),
    "lucknow": ("Lucknow", "Uttar Pradesh"),
    "maharajganj": ("Maharajganj", "Uttar Pradesh"),
    "mahoba": ("Mahoba", "Uttar Pradesh"),
    "mainpuri": ("Mainpuri", "Uttar Pradesh"),
    "mathura": ("Mathura", "Uttar Pradesh"),
    "mau": ("Mau", "Uttar Pradesh"),
    "meerut": ("Meerut", "Uttar Pradesh"),
    "mirzapur": ("Mirzapur", "Uttar Pradesh"),
    "moradabad": ("Moradabad", "Uttar Pradesh"),
    "muzaffarnagar": ("Muzaffarnagar", "Uttar Pradesh"),
    "pilibhit": ("Pilibhit", "Uttar Pradesh"),
    "pratapgarh": ("Pratapgarh", "Uttar Pradesh"),
    "prayagraj": ("Prayagraj", "Uttar Pradesh"),
    "allahabad": ("Prayagraj", "Uttar Pradesh"),
    "raebareli": ("Raebareli", "Uttar Pradesh"),
    "rampur": ("Rampur", "Uttar Pradesh"),
    "saharanpur": ("Saharanpur", "Uttar Pradesh"),
    "sambhal": ("Sambhal", "Uttar Pradesh"),
    "sant kabir nagar": ("Sant Kabir Nagar", "Uttar Pradesh"),
    "shahjahanpur": ("Shahjahanpur", "Uttar Pradesh"),
    "shamli": ("Shamli", "Uttar Pradesh"),
    "shravasti": ("Shravasti", "Uttar Pradesh"),
    "siddharthnagar": ("Siddharthnagar", "Uttar Pradesh"),
    "sitapur": ("Sitapur", "Uttar Pradesh"),
    "sonbhadra": ("Sonbhadra", "Uttar Pradesh"),
    "sultanpur": ("Sultanpur", "Uttar Pradesh"),
    "unnao": ("Unnao", "Uttar Pradesh"),
    "varanasi": ("Varanasi", "Uttar Pradesh"),
    "banaras": ("Varanasi", "Uttar Pradesh"),
    "kashi": ("Varanasi", "Uttar Pradesh"),

    # Bihar
    "araria": ("Araria", "Bihar"),
    "arwal": ("Arwal", "Bihar"),
    "aurangabad bihar": ("Aurangabad", "Bihar"),
    "banka": ("Banka", "Bihar"),
    "begusarai": ("Begusarai", "Bihar"),
    "bhagalpur": ("Bhagalpur", "Bihar"),
    "bhojpur": ("Bhojpur", "Bihar"),
    "arrah": ("Bhojpur", "Bihar"),
    "buxar": ("Buxar", "Bihar"),
    "darbhanga": ("Darbhanga", "Bihar"),
    "east champaran": ("East Champaran", "Bihar"),
    "motihari": ("East Champaran", "Bihar"),
    "gaya": ("Gaya", "Bihar"),
    "gopalganj": ("Gopalganj", "Bihar"),
    "jamui": ("Jamui", "Bihar"),
    "jehanabad": ("Jehanabad", "Bihar"),
    "kaimur": ("Kaimur", "Bihar"),
    "bhabua": ("Kaimur", "Bihar"),
    "katihar": ("Katihar", "Bihar"),
    "khagaria": ("Khagaria", "Bihar"),
    "kishanganj": ("Kishanganj", "Bihar"),
    "lakhisarai": ("Lakhisarai", "Bihar"),
    "madhepura": ("Madhepura", "Bihar"),
    "madhubani": ("Madhubani", "Bihar"),
    "munger": ("Munger", "Bihar"),
    "muzaffarpur": ("Muzaffarpur", "Bihar"),
    "nalanda": ("Nalanda", "Bihar"),
    "bihar sharif": ("Nalanda", "Bihar"),
    "nawada": ("Nawada", "Bihar"),
    "patna": ("Patna", "Bihar"),
    "purnia": ("Purnia", "Bihar"),
    "rohtas": ("Rohtas", "Bihar"),
    "sasaram": ("Rohtas", "Bihar"),
    "saharsa": ("Saharsa", "Bihar"),
    "samastipur": ("Samastipur", "Bihar"),
    "saran": ("Saran", "Bihar"),
    "chhapra": ("Saran", "Bihar"),
    "sheikhpura": ("Sheikhpura", "Bihar"),
    "sheohar": ("Sheohar", "Bihar"),
    "sitamarhi": ("Sitamarhi", "Bihar"),
    "siwan": ("Siwan", "Bihar"),
    "supaul": ("Supaul", "Bihar"),
    "vaishali": ("Vaishali", "Bihar"),
    "hajipur": ("Vaishali", "Bihar"),
    "west champaran": ("West Champaran", "Bihar"),
    "bettiah": ("West Champaran", "Bihar"),

    # Madhya Pradesh
    "agar malwa": ("Agar Malwa", "Madhya Pradesh"),
    "alirajpur": ("Alirajpur", "Madhya Pradesh"),
    "anuppur": ("Anuppur", "Madhya Pradesh"),
    "ashoknagar": ("Ashoknagar", "Madhya Pradesh"),
    "balaghat": ("Balaghat", "Madhya Pradesh"),
    "barwani": ("Barwani", "Madhya Pradesh"),
    "betul": ("Betul", "Madhya Pradesh"),
    "bhind": ("Bhind", "Madhya Pradesh"),
    "bhopal": ("Bhopal", "Madhya Pradesh"),
    "burhanpur": ("Burhanpur", "Madhya Pradesh"),
    "chhatarpur": ("Chhatarpur", "Madhya Pradesh"),
    "chhindwara": ("Chhindwara", "Madhya Pradesh"),
    "damoh": ("Damoh", "Madhya Pradesh"),
    "datia": ("Datia", "Madhya Pradesh"),
    "dewas": ("Dewas", "Madhya Pradesh"),
    "dhar": ("Dhar", "Madhya Pradesh"),
    "dindori": ("Dindori", "Madhya Pradesh"),
    "guna": ("Guna", "Madhya Pradesh"),
    "gwalior": ("Gwalior", "Madhya Pradesh"),
    "harda": ("Harda", "Madhya Pradesh"),
    "narmadapuram": ("Narmadapuram", "Madhya Pradesh"),
    "hoshangabad": ("Narmadapuram", "Madhya Pradesh"),
    "indore": ("Indore", "Madhya Pradesh"),
    "jabalpur": ("Jabalpur", "Madhya Pradesh"),
    "jhabua": ("Jhabua", "Madhya Pradesh"),
    "katni": ("Katni", "Madhya Pradesh"),
    "khandwa": ("Khandwa", "Madhya Pradesh"),
    "khargone": ("Khargone", "Madhya Pradesh"),
    "mandla": ("Mandla", "Madhya Pradesh"),
    "mandsaur": ("Mandsaur", "Madhya Pradesh"),
    "morena": ("Morena", "Madhya Pradesh"),
    "narsinghpur": ("Narsinghpur", "Madhya Pradesh"),
    "neemuch": ("Neemuch", "Madhya Pradesh"),
    "niwari": ("Niwari", "Madhya Pradesh"),
    "panna": ("Panna", "Madhya Pradesh"),
    "raisen": ("Raisen", "Madhya Pradesh"),
    "rajgarh": ("Rajgarh", "Madhya Pradesh"),
    "ratlam": ("Ratlam", "Madhya Pradesh"),
    "rewa": ("Rewa", "Madhya Pradesh"),
    "sagar": ("Sagar", "Madhya Pradesh"),
    "satna": ("Satna", "Madhya Pradesh"),
    "sehore": ("Sehore", "Madhya Pradesh"),
    "seoni": ("Seoni", "Madhya Pradesh"),
    "shahdol": ("Shahdol", "Madhya Pradesh"),
    "shajapur": ("Shajapur", "Madhya Pradesh"),
    "sheopur": ("Sheopur", "Madhya Pradesh"),
    "shivpuri": ("Shivpuri", "Madhya Pradesh"),
    "sidhi": ("Sidhi", "Madhya Pradesh"),
    "singrauli": ("Singrauli", "Madhya Pradesh"),
    "tikamgarh": ("Tikamgarh", "Madhya Pradesh"),
    "ujjain": ("Ujjain", "Madhya Pradesh"),
    "umaria": ("Umaria", "Madhya Pradesh"),
    "vidisha": ("Vidisha", "Madhya Pradesh"),

    # Rajasthan
    "ajmer": ("Ajmer", "Rajasthan"),
    "alwar": ("Alwar", "Rajasthan"),
    "banswara": ("Banswara", "Rajasthan"),
    "baran": ("Baran", "Rajasthan"),
    "barmer": ("Barmer", "Rajasthan"),
    "bharatpur": ("Bharatpur", "Rajasthan"),
    "bhilwara": ("Bhilwara", "Rajasthan"),
    "bikaner": ("Bikaner", "Rajasthan"),
    "bundi": ("Bundi", "Rajasthan"),
    "chittorgarh": ("Chittorgarh", "Rajasthan"),
    "churu": ("Churu", "Rajasthan"),
    "dausa": ("Dausa", "Rajasthan"),
    "dholpur": ("Dholpur", "Rajasthan"),
    "dungarpur": ("Dungarpur", "Rajasthan"),
    "hanumangarh": ("Hanumangarh", "Rajasthan"),
    "jaipur": ("Jaipur", "Rajasthan"),
    "jaisalmer": ("Jaisalmer", "Rajasthan"),
    "jalore": ("Jalore", "Rajasthan"),
    "jhalawar": ("Jhalawar", "Rajasthan"),
    "jhunjhunu": ("Jhunjhunu", "Rajasthan"),
    "jodhpur": ("Jodhpur", "Rajasthan"),
    "karauli": ("Karauli", "Rajasthan"),
    "kota": ("Kota", "Rajasthan"),
    "nagaur": ("Nagaur", "Rajasthan"),
    "pali": ("Pali", "Rajasthan"),
    "pratapgarh rajasthan": ("Pratapgarh", "Rajasthan"),
    "rajsamand": ("Rajsamand", "Rajasthan"),
    "sawai madhopur": ("Sawai Madhopur", "Rajasthan"),
    "sikar": ("Sikar", "Rajasthan"),
    "sirohi": ("Sirohi", "Rajasthan"),
    "sri ganganagar": ("Sri Ganganagar", "Rajasthan"),
    "ganganagar": ("Sri Ganganagar", "Rajasthan"),
    "tonk": ("Tonk", "Rajasthan"),
    "udaipur": ("Udaipur", "Rajasthan"),

    # Maharashtra
    "ahmednagar": ("Ahmednagar", "Maharashtra"),
    "akola": ("Akola", "Maharashtra"),
    "amravati": ("Amravati", "Maharashtra"),
    "aurangabad": ("Chhatrapati Sambhajinagar", "Maharashtra"),
    "chhatrapati sambhajinagar": ("Chhatrapati Sambhajinagar", "Maharashtra"),
    "beed": ("Beed", "Maharashtra"),
    "bhandara": ("Bhandara", "Maharashtra"),
    "buldhana": ("Buldhana", "Maharashtra"),
    "chandrapur": ("Chandrapur", "Maharashtra"),
    "dhule": ("Dhule", "Maharashtra"),
    "gadchiroli": ("Gadchiroli", "Maharashtra"),
    "gondia": ("Gondia", "Maharashtra"),
    "hingoli": ("Hingoli", "Maharashtra"),
    "jalgaon": ("Jalgaon", "Maharashtra"),
    "jalna": ("Jalna", "Maharashtra"),
    "kolhapur": ("Kolhapur", "Maharashtra"),
    "latur": ("Latur", "Maharashtra"),
    "mumbai": ("Mumbai", "Maharashtra"),
    "mumbai suburban": ("Mumbai Suburban", "Maharashtra"),
    "nagpur": ("Nagpur", "Maharashtra"),
    "nanded": ("Nanded", "Maharashtra"),
    "nandurbar": ("Nandurbar", "Maharashtra"),
    "nashik": ("Nashik", "Maharashtra"),
    "osmanabad": ("Dharashiv", "Maharashtra"),
    "dharashiv": ("Dharashiv", "Maharashtra"),
    "palghar": ("Palghar", "Maharashtra"),
    "parbhani": ("Parbhani", "Maharashtra"),
    "pune": ("Pune", "Maharashtra"),
    "raigad": ("Raigad", "Maharashtra"),
    "ratnagiri": ("Ratnagiri", "Maharashtra"),
    "sangli": ("Sangli", "Maharashtra"),
    "satara": ("Satara", "Maharashtra"),
    "sindhudurg": ("Sindhudurg", "Maharashtra"),
    "solapur": ("Solapur", "Maharashtra"),
    "thane": ("Thane", "Maharashtra"),
    "wardha": ("Wardha", "Maharashtra"),
    "washim": ("Washim", "Maharashtra"),
    "yavatmal": ("Yavatmal", "Maharashtra"),

    # Gujarat
    "ahmedabad": ("Ahmedabad", "Gujarat"),
    "amreli": ("Amreli", "Gujarat"),
    "anand": ("Anand", "Gujarat"),
    "aravalli": ("Aravalli", "Gujarat"),
    "banaskantha": ("Banaskantha", "Gujarat"),
    "bharuch": ("Bharuch", "Gujarat"),
    "bhavnagar": ("Bhavnagar", "Gujarat"),
    "botad": ("Botad", "Gujarat"),
    "chhota udepur": ("Chhota Udepur", "Gujarat"),
    "dahod": ("Dahod", "Gujarat"),
    "dang": ("Dang", "Gujarat"),
    "devbhoomi dwarka": ("Devbhoomi Dwarka", "Gujarat"),
    "gandhinagar": ("Gandhinagar", "Gujarat"),
    "gir somnath": ("Gir Somnath", "Gujarat"),
    "jamnagar": ("Jamnagar", "Gujarat"),
    "junagadh": ("Junagadh", "Gujarat"),
    "kutch": ("Kutch", "Gujarat"),
    "kheda": ("Kheda", "Gujarat"),
    "mahisagar": ("Mahisagar", "Gujarat"),
    "mehsana": ("Mehsana", "Gujarat"),
    "morbi": ("Morbi", "Gujarat"),
    "narmada": ("Narmada", "Gujarat"),
    "navsari": ("Navsari", "Gujarat"),
    "panchmahal": ("Panchmahal", "Gujarat"),
    "patan": ("Patan", "Gujarat"),
    "porbandar": ("Porbandar", "Gujarat"),
    "rajkot": ("Rajkot", "Gujarat"),
    "sabarkantha": ("Sabarkantha", "Gujarat"),
    "surat": ("Surat", "Gujarat"),
    "surendranagar": ("Surendranagar", "Gujarat"),
    "tapi": ("Tapi", "Gujarat"),
    "vadodara": ("Vadodara", "Gujarat"),
    "baroda": ("Vadodara", "Gujarat"),
    "valsad": ("Valsad", "Gujarat"),

    # West Bengal
    "alipurduar": ("Alipurduar", "West Bengal"),
    "bankura": ("Bankura", "West Bengal"),
    "birbhum": ("Birbhum", "West Bengal"),
    "cooch behar": ("Cooch Behar", "West Bengal"),
    "dakshin dinajpur": ("Dakshin Dinajpur", "West Bengal"),
    "darjeeling": ("Darjeeling", "West Bengal"),
    "hooghly": ("Hooghly", "West Bengal"),
    "howrah": ("Howrah", "West Bengal"),
    "jalpaiguri": ("Jalpaiguri", "West Bengal"),
    "jhargram": ("Jhargram", "West Bengal"),
    "kalimpong": ("Kalimpong", "West Bengal"),
    "kolkata": ("Kolkata", "West Bengal"),
    "calcutta": ("Kolkata", "West Bengal"),
    "malda": ("Malda", "West Bengal"),
    "murshidabad": ("Murshidabad", "West Bengal"),
    "nadia": ("Nadia", "West Bengal"),
    "north 24 parganas": ("North 24 Parganas", "West Bengal"),
    "paschim bardhaman": ("Paschim Bardhaman", "West Bengal"),
    "paschim medinipur": ("Paschim Medinipur", "West Bengal"),
    "purba bardhaman": ("Purba Bardhaman", "West Bengal"),
    "purba medinipur": ("Purba Medinipur", "West Bengal"),
    "purulia": ("Purulia", "West Bengal"),
    "south 24 parganas": ("South 24 Parganas", "West Bengal"),
    "uttar dinajpur": ("Uttar Dinajpur", "West Bengal"),

    # Karnataka
    "bagalkot": ("Bagalkot", "Karnataka"),
    "ballari": ("Ballari", "Karnataka"),
    "bellary": ("Ballari", "Karnataka"),
    "belagavi": ("Belagavi", "Karnataka"),
    "belgaum": ("Belagavi", "Karnataka"),
    "bengaluru rural": ("Bengaluru Rural", "Karnataka"),
    "bengaluru urban": ("Bengaluru Urban", "Karnataka"),
    "bengaluru": ("Bengaluru Urban", "Karnataka"),
    "bangalore": ("Bengaluru Urban", "Karnataka"),
    "bidar": ("Bidar", "Karnataka"),
    "chamarajanagar": ("Chamarajanagar", "Karnataka"),
    "chikkaballapur": ("Chikkaballapur", "Karnataka"),
    "chikkamagaluru": ("Chikkamagaluru", "Karnataka"),
    "chitradurga": ("Chitradurga", "Karnataka"),
    "dakshina kannada": ("Dakshina Kannada", "Karnataka"),
    "mangalore": ("Dakshina Kannada", "Karnataka"),
    "davanagere": ("Davanagere", "Karnataka"),
    "dharwad": ("Dharwad", "Karnataka"),
    "hubli": ("Dharwad", "Karnataka"),
    "gadag": ("Gadag", "Karnataka"),
    "hassan": ("Hassan", "Karnataka"),
    "haveri": ("Haveri", "Karnataka"),
    "kalaburagi": ("Kalaburagi", "Karnataka"),
    "gulbarga": ("Kalaburagi", "Karnataka"),
    "kodagu": ("Kodagu", "Karnataka"),
    "coorg": ("Kodagu", "Karnataka"),
    "kolar": ("Kolar", "Karnataka"),
    "koppal": ("Koppal", "Karnataka"),
    "mandya": ("Mandya", "Karnataka"),
    "mysuru": ("Mysuru", "Karnataka"),
    "mysore": ("Mysuru", "Karnataka"),
    "raichur": ("Raichur", "Karnataka"),
    "ramanagara": ("Ramanagara", "Karnataka"),
    "shivamogga": ("Shivamogga", "Karnataka"),
    "shimoga": ("Shivamogga", "Karnataka"),
    "tumakuru": ("Tumakuru", "Karnataka"),
    "tumkur": ("Tumakuru", "Karnataka"),
    "udupi": ("Udupi", "Karnataka"),
    "uttara kannada": ("Uttara Kannada", "Karnataka"),
    "karwar": ("Uttara Kannada", "Karnataka"),
    "vijayanagara": ("Vijayanagara", "Karnataka"),
    "yadgir": ("Yadgir", "Karnataka"),

    # Tamil Nadu
    "ariyalur": ("Ariyalur", "Tamil Nadu"),
    "chengalpattu": ("Chengalpattu", "Tamil Nadu"),
    "chennai": ("Chennai", "Tamil Nadu"),
    "madras": ("Chennai", "Tamil Nadu"),
    "coimbatore": ("Coimbatore", "Tamil Nadu"),
    "cuddalore": ("Cuddalore", "Tamil Nadu"),
    "dharmapuri": ("Dharmapuri", "Tamil Nadu"),
    "dindigul": ("Dindigul", "Tamil Nadu"),
    "erode": ("Erode", "Tamil Nadu"),
    "kallakurichi": ("Kallakurichi", "Tamil Nadu"),
    "kanchipuram": ("Kanchipuram", "Tamil Nadu"),
    "kanyakumari": ("Kanyakumari", "Tamil Nadu"),
    "karur": ("Karur", "Tamil Nadu"),
    "krishnagiri": ("Krishnagiri", "Tamil Nadu"),
    "madurai": ("Madurai", "Tamil Nadu"),
    "mayiladuthurai": ("Mayiladuthurai", "Tamil Nadu"),
    "nagapattinam": ("Nagapattinam", "Tamil Nadu"),
    "namakkal": ("Namakkal", "Tamil Nadu"),
    "nilgiris": ("Nilgiris", "Tamil Nadu"),
    "ooty": ("Nilgiris", "Tamil Nadu"),
    "perambalur": ("Perambalur", "Tamil Nadu"),
    "pudukkottai": ("Pudukkottai", "Tamil Nadu"),
    "ramanathapuram": ("Ramanathapuram", "Tamil Nadu"),
    "ranipet": ("Ranipet", "Tamil Nadu"),
    "salem": ("Salem", "Tamil Nadu"),
    "sivaganga": ("Sivaganga", "Tamil Nadu"),
    "tenkasi": ("Tenkasi", "Tamil Nadu"),
    "thanjavur": ("Thanjavur", "Tamil Nadu"),
    "theni": ("Theni", "Tamil Nadu"),
    "thoothukudi": ("Thoothukudi", "Tamil Nadu"),
    "tuticorin": ("Thoothukudi", "Tamil Nadu"),
    "tiruchirappalli": ("Tiruchirappalli", "Tamil Nadu"),
    "trichy": ("Tiruchirappalli", "Tamil Nadu"),
    "tirunelveli": ("Tirunelveli", "Tamil Nadu"),
    "tirupathur": ("Tirupathur", "Tamil Nadu"),
    "tiruppur": ("Tiruppur", "Tamil Nadu"),
    "tiruvallur": ("Tiruvallur", "Tamil Nadu"),
    "tiruvannamalai": ("Tiruvannamalai", "Tamil Nadu"),
    "tiruvarur": ("Tiruvarur", "Tamil Nadu"),
    "vellore": ("Vellore", "Tamil Nadu"),
    "viluppuram": ("Viluppuram", "Tamil Nadu"),
    "virudhunagar": ("Virudhunagar", "Tamil Nadu"),

    # Andhra Pradesh & Telangana
    "anantapur": ("Anantapur", "Andhra Pradesh"),
    "chittoor": ("Chittoor", "Andhra Pradesh"),
    "east godavari": ("East Godavari", "Andhra Pradesh"),
    "guntur": ("Guntur", "Andhra Pradesh"),
    "kadapa": ("YSR Kadapa", "Andhra Pradesh"),
    "krishna": ("Krishna", "Andhra Pradesh"),
    "kurnool": ("Kurnool", "Andhra Pradesh"),
    "nellore": ("SPSR Nellore", "Andhra Pradesh"),
    "prakasam": ("Prakasam", "Andhra Pradesh"),
    "srikakulam": ("Srikakulam", "Andhra Pradesh"),
    "visakhapatnam": ("Visakhapatnam", "Andhra Pradesh"),
    "vizag": ("Visakhapatnam", "Andhra Pradesh"),
    "vizianagaram": ("Vizianagaram", "Andhra Pradesh"),
    "west godavari": ("West Godavari", "Andhra Pradesh"),
    "hyderabad": ("Hyderabad", "Telangana"),
    "karimnagar": ("Karimnagar", "Telangana"),
    "khammam": ("Khammam", "Telangana"),
    "mahbubnagar": ("Mahabubnagar", "Telangana"),
    "nalgonda": ("Nalgonda", "Telangana"),
    "nizamabad": ("Nizamabad", "Telangana"),
    "rangareddy": ("Rangareddy", "Telangana"),
    "warangal": ("Warangal", "Telangana"),

    # Odisha / Orissa
    "angul": ("Angul", "Odisha"),
    "balangir": ("Balangir", "Odisha"),
    "balasore": ("Balasore", "Odisha"),
    "baleshwar": ("Balasore", "Odisha"),
    "bargarh": ("Bargarh", "Odisha"),
    "bhadrak": ("Bhadrak", "Odisha"),
    "cuttack": ("Cuttack", "Odisha"),
    "deogarh": ("Deogarh", "Odisha"),
    "dhenkanal": ("Dhenkanal", "Odisha"),
    "gajapati": ("Gajapati", "Odisha"),
    "ganjam": ("Ganjam", "Odisha"),
    "jagatsinghpur": ("Jagatsinghpur", "Odisha"),
    "jajpur": ("Jajpur", "Odisha"),
    "jharsuguda": ("Jharsuguda", "Odisha"),
    "kalahandi": ("Kalahandi", "Odisha"),
    "kandhamal": ("Kandhamal", "Odisha"),
    "kendrapara": ("Kendrapara", "Odisha"),
    "kendujhar": ("Kendujhar", "Odisha"),
    "keonjhar": ("Kendujhar", "Odisha"),
    "khordha": ("Khordha", "Odisha"),
    "bhubaneswar": ("Khordha", "Odisha"),
    "koraput": ("Koraput", "Odisha"),
    "malkangiri": ("Malkangiri", "Odisha"),
    "mayurbhanj": ("Mayurbhanj", "Odisha"),
    "nabarangpur": ("Nabarangpur", "Odisha"),
    "nayagarh": ("Nayagarh", "Odisha"),
    "nuapada": ("Nuapada", "Odisha"),
    "puri": ("Puri", "Odisha"),
    "rayagada": ("Rayagada", "Odisha"),
    "sambalpur": ("Sambalpur", "Odisha"),
    "subarnapur": ("Subarnapur", "Odisha"),
    "sonepur": ("Subarnapur", "Odisha"),
    "sundargarh": ("Sundargarh", "Odisha"),

    # Jharkhand & Chhattisgarh
    "bokaro": ("Bokaro", "Jharkhand"),
    "deoghar": ("Deoghar", "Jharkhand"),
    "dhanbad": ("Dhanbad", "Jharkhand"),
    "dumka": ("Dumka", "Jharkhand"),
    "hazaribagh": ("Hazaribagh", "Jharkhand"),
    "jamshedpur": ("East Singhbhum", "Jharkhand"),
    "ranchi": ("Ranchi", "Jharkhand"),
    "bilaspur": ("Bilaspur", "Chhattisgarh"),
    "durg": ("Durg", "Chhattisgarh"),
    "raipur": ("Raipur", "Chhattisgarh"),
    "rajnandgaon": ("Rajnandgaon", "Chhattisgarh"),

    # Kerala
    "alappuzha": ("Alappuzha", "Kerala"),
    "ernakulam": ("Ernakulam", "Kerala"),
    "kochi": ("Ernakulam", "Kerala"),
    "idukki": ("Idukki", "Kerala"),
    "kannur": ("Kannur", "Kerala"),
    "kasaragod": ("Kasaragod", "Kerala"),
    "kollam": ("Kollam", "Kerala"),
    "kottayam": ("Kottayam", "Kerala"),
    "kozhikode": ("Kozhikode", "Kerala"),
    "calicut": ("Kozhikode", "Kerala"),
    "malappuram": ("Malappuram", "Kerala"),
    "palakkad": ("Palakkad", "Kerala"),
    "pathanamthitta": ("Pathanamthitta", "Kerala"),
    "thiruvananthapuram": ("Thiruvananthapuram", "Kerala"),
    "trivandrum": ("Thiruvananthapuram", "Kerala"),
    "thrissur": ("Thrissur", "Kerala"),
    "wayanad": ("Wayanad", "Kerala"),

    # Assam & Northeast
    "barpeta": ("Barpeta", "Assam"),
    "cachar": ("Cachar", "Assam"),
    "silchar": ("Cachar", "Assam"),
    "darrang": ("Darrang", "Assam"),
    "dibrugarh": ("Dibrugarh", "Assam"),
    "goalpara": ("Goalpara", "Assam"),
    "golaghat": ("Golaghat", "Assam"),
    "kamrup metropolitan": ("Kamrup Metropolitan", "Assam"),
    "kamrup": ("Kamrup", "Assam"),
    "guwahati": ("Kamrup Metropolitan", "Assam"),
    "nagaon": ("Nagaon", "Assam"),
    "sonitpur": ("Sonitpur", "Assam"),
    "tezpur": ("Sonitpur", "Assam"),
    "tinsukia": ("Tinsukia", "Assam"),

    # Himachal & Uttarakhand & J&K
    "kangra": ("Kangra", "Himachal Pradesh"),
    "mandi district": ("Mandi", "Himachal Pradesh"),
    "shimla": ("Shimla", "Himachal Pradesh"),
    "solan": ("Solan", "Himachal Pradesh"),
    "dehradun": ("Dehradun", "Uttarakhand"),
    "haridwar": ("Haridwar", "Uttarakhand"),
    "nainital": ("Nainital", "Uttarakhand"),
    "udham singh nagar": ("Udham Singh Nagar", "Uttarakhand"),
    "jammu": ("Jammu", "Jammu and Kashmir"),
    "srinagar": ("Srinagar", "Jammu and Kashmir"),
    "anantnag": ("Anantnag", "Jammu and Kashmir"),
    "baramulla": ("Baramulla", "Jammu and Kashmir"),
}

import re
from typing import Tuple, Optional

def extract_indian_location(query: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Extracts (state, district) from a farmer's message.
    Matches districts first (which map directly to their home state),
    then matches standalone states.
    
    Returns:
        (state_name, district_name)
    """
    if not query:
        return None, None
    
    q = query.lower()
    
    detected_district = None
    detected_state = None
    
    # 1. Match district first (longest match priority)
    # Sort districts by length descending to match "gautam buddha nagar" before "nagar"
    sorted_districts = sorted(INDIAN_DISTRICTS.keys(), key=len, reverse=True)
    for dist_key in sorted_districts:
        # Match as whole word or boundary
        pattern = r'\b' + re.escape(dist_key) + r'\b'
        if re.search(pattern, q):
            canon_dist, canon_st = INDIAN_DISTRICTS[dist_key]
            detected_district = canon_dist
            detected_state = canon_st
            break
            
    # 2. Check for explicit state mentioned in the query
    sorted_states = sorted(INDIAN_STATES.keys(), key=len, reverse=True)
    for st_key in sorted_states:
        pattern = r'\b' + re.escape(st_key) + r'\b'
        if re.search(pattern, q):
            explicit_st = INDIAN_STATES[st_key]
            detected_state = explicit_st
            break
            
    return detected_state, detected_district
