export const locationOptions = {
  'Andhra Pradesh': {
    'Anantapur': ['Anantapur', 'Hindupur', 'Guntakal', 'Dharmavaram', 'Kadiri', 'Penukonda'],
    'Chittoor': ['Chittoor', 'Tirupati', 'Madanapalle', 'Palamaner', 'Punganur', 'Srikalahasti'],
    'East Godavari': ['Kakinada', 'Rajahmundry', 'Amalapuram', 'Ramachandrapuram', 'Peddapuram'],
    'Guntur': ['Guntur', 'Tenali', 'Mangalagiri', 'Narasaraopet', 'Bapatla', 'Sattenapalli'],
    'Krishna': ['Vijayawada', 'Machilipatnam', 'Gudivada', 'Jaggayyapeta', 'Nuzvid'],
    'Kurnool': ['Kurnool', 'Nandyal', 'Adoni', 'Yemmiganur', 'Dhone'],
    'Nellore': ['Nellore', 'Kavali', 'Gudur', 'Atmakur', 'Sullurpeta'],
    'Prakasam': ['Ongole', 'Chirala', 'Markapur', 'Kandukur', 'Darsi'],
    'Srikakulam': ['Srikakulam', 'Palasa', 'Amadalavalasa', 'Narasannapeta'],
    'Visakhapatnam': ['Visakhapatnam', 'Anakapalli', 'Gajuwaka', 'Narsipatnam'],
    'Vizianagaram': ['Vizianagaram', 'Bobbili', 'Parvathipuram', 'Salur'],
    'West Godavari': ['Eluru', 'Bhimavaram', 'Tadepalligudem', 'Tanuku', 'Narsapur'],
    'YSR Kadapa': ['Kadapa', 'Proddatur', 'Rajampet', 'Pulivendla', 'Jammalamadugu'],
  },
  'Assam': {
    'Kamrup Metropolitan': ['Guwahati', 'Dispur', 'North Guwahati'],
    'Dibrugarh': ['Dibrugarh', 'Naharkatiya', 'Chabua'],
    'Jorhat': ['Jorhat', 'Mariani', 'Titabor'],
    'Nagaon': ['Nagaon', 'Hojai', 'Lanka'],
    'Sonitpur': ['Tezpur', 'Rangapara', 'Dhekiajuli'],
    'Cachar': ['Silchar', 'Hailakandi', 'Lakhipur'],
    'Tinsukia': ['Tinsukia', 'Digboi', 'Margherita'],
  },
  'Bihar': {
    'Patna': ['Patna', 'Danapur', 'Phulwari', 'Barh', 'Masaurhi', 'Bikram'],
    'Gaya': ['Gaya', 'Bodh Gaya', 'Sherghati', 'Tekari', 'Atri'],
    'Muzaffarpur': ['Muzaffarpur', 'Sitamarhi', 'Motihari', 'Hajipur'],
    'Bhagalpur': ['Bhagalpur', 'Sultanganj', 'Naugachhia', 'Kahalgaon'],
    'Darbhanga': ['Darbhanga', 'Laheriasarai', 'Benipur', 'Hayaghat'],
    'Begusarai': ['Begusarai', 'Barauni', 'Teghra', 'Bachhwara'],
    'Nalanda': ['Bihar Sharif', 'Rajgir', 'Hilsa', 'Ekangarsarai'],
    'Vaishali': ['Hajipur', 'Mahua', 'Raghopur', 'Bidupur'],
    'Samastipur': ['Samastipur', 'Rosera', 'Patori', 'Dalsinghsarai'],
    'Purnia': ['Purnia', 'Kasba', 'Dhamdaha', 'Baisi'],
    'Saran': ['Chhapra', 'Marhaura', 'Revelganj', 'Dighwara'],
    'Madhubani': ['Madhubani', 'Jhanjharpur', 'Benipatti', 'Laukahi'],
  },
  'Chhattisgarh': {
    'Raipur': ['Raipur', 'Aarang', 'Abhanpur', 'Tilda'],
    'Bilaspur': ['Bilaspur', 'Mungeli', 'Lormi', 'Takhatpur'],
    'Durg': ['Durg', 'Bhilai', 'Rajnandgaon', 'Dhamtari'],
    'Korba': ['Korba', 'Katghora', 'Pali'],
    'Jagdalpur': ['Jagdalpur', 'Kondagaon', 'Kanker'],
  },
  'Delhi': {
    'New Delhi': ['Connaught Place', 'Chanakyapuri', 'Lajpat Nagar', 'Sarojini Nagar'],
    'Central Delhi': ['Karol Bagh', 'Paharganj', 'Daryaganj'],
    'South Delhi': ['Mehrauli', 'Hauz Khas', 'Greater Kailash', 'Saket'],
    'North Delhi': ['Civil Lines', 'Model Town', 'Alipur', 'Narela'],
    'East Delhi': ['Preet Vihar', 'Laxmi Nagar', 'Mayur Vihar'],
    'West Delhi': ['Janakpuri', 'Rajouri Garden', 'Punjabi Bagh', 'Tilak Nagar'],
  },
  'Goa': {
    'North Goa': ['Panaji', 'Mapusa', 'Bicholim', 'Pernem', 'Bardez'],
    'South Goa': ['Margao', 'Vasco da Gama', 'Ponda', 'Quepem', 'Canacona'],
  },
  'Gujarat': {
    'Ahmedabad': ['Ahmedabad', 'Dhandhuka', 'Dholka', 'Sanand', 'Viramgam'],
    'Surat': ['Surat', 'Bardoli', 'Kamrej', 'Mandvi', 'Olpad'],
    'Vadodara': ['Vadodara', 'Dabhoi', 'Padra', 'Savli', 'Karjan'],
    'Rajkot': ['Rajkot', 'Dhoraji', 'Gondal', 'Jetpur', 'Morbi'],
    'Bhavnagar': ['Bhavnagar', 'Palitana', 'Sihor', 'Mahuva', 'Gariadhar'],
    'Junagadh': ['Junagadh', 'Veraval', 'Keshod', 'Manavadar'],
    'Kutch': ['Bhuj', 'Anjar', 'Gandhidham', 'Mundra', 'Mandvi'],
    'Mehsana': ['Mehsana', 'Visnagar', 'Unjha', 'Kadi', 'Patan'],
    'Banaskantha': ['Palanpur', 'Deesa', 'Dhanera', 'Tharad'],
    'Anand': ['Anand', 'Khambhat', 'Petlad', 'Borsad', 'Umreth'],
  },
  'Haryana': {
    'Ambala': ['Ambala', 'Barara', 'Naraingarh', 'Shahzadpur'],
    'Bhiwani': ['Bhiwani', 'Charkhi Dadri', 'Loharu', 'Siwani'],
    'Faridabad': ['Faridabad', 'Ballabgarh', 'Palwal'],
    'Fatehabad': ['Fatehabad', 'Tohana', 'Ratia', 'Jakhal'],
    'Gurugram': ['Gurugram', 'Sohna', 'Pataudi', 'Manesar', 'Farukhnagar'],
    'Hisar': ['Hisar', 'Hansi', 'Adampur', 'Barwala', 'Uklana'],
    'Jhajjar': ['Jhajjar', 'Bahadurgarh', 'Beri', 'Machhrauli'],
    'Jind': ['Jind', 'Narwana', 'Safidon', 'Julana', 'Uchana'],
    'Kaithal': ['Kaithal', 'Pundri', 'Kalayat', 'Guhla'],
    'Karnal': ['Karnal', 'Assandh', 'Indri', 'Nilokheri', 'Gharaunda'],
    'Kurukshetra': ['Kurukshetra', 'Thanesar', 'Pehowa', 'Shahabad', 'Ladwa'],
    'Mahendragarh': ['Narnaul', 'Mahendragarh', 'Ateli'],
    'Nuh': ['Nuh', 'Ferozepur Jhirka', 'Punhana', 'Taoru'],
    'Panipat': ['Panipat', 'Samalkha', 'Israna', 'Madlauda'],
    'Panchkula': ['Panchkula', 'Kalka', 'Barwala', 'Raipur Rani'],
    'Rewari': ['Rewari', 'Bawal', 'Kosli', 'Dharuhera'],
    'Rohtak': ['Rohtak', 'Meham', 'Kalanaur', 'Sampla'],
    'Sirsa': ['Sirsa', 'Rania', 'Dabwali', 'Ellenabad'],
    'Sonipat': ['Sonipat', 'Gohana', 'Ganaur', 'Kharkhoda'],
    'Yamunanagar': ['Yamunanagar', 'Jagadhri', 'Radaur', 'Chhachhrauli'],
  },
  'Himachal Pradesh': {
    'Shimla': ['Shimla', 'Theog', 'Rampur', 'Rohru', 'Jubbal'],
    'Kangra': ['Dharamshala', 'Kangra', 'Palampur', 'Baijnath', 'Nurpur'],
    'Mandi': ['Mandi', 'Sundernagar', 'Joginder Nagar', 'Sarkaghat'],
    'Kullu': ['Kullu', 'Manali', 'Bhuntar', 'Banjar'],
    'Solan': ['Solan', 'Nalagarh', 'Baddi', 'Kasauli', 'Arki'],
    'Sirmaur': ['Nahan', 'Paonta Sahib', 'Rajgarh'],
    'Una': ['Una', 'Amb', 'Gagret', 'Haroli'],
    'Hamirpur': ['Hamirpur', 'Nadaun', 'Barsar', 'Sujanpur'],
  },
  'Jharkhand': {
    'Ranchi': ['Ranchi', 'Namkum', 'Kanke', 'Bundu', 'Tamar'],
    'Jamshedpur': ['Jamshedpur', 'Gamharia', 'Adityapur', 'Seraikela'],
    'Dhanbad': ['Dhanbad', 'Jharia', 'Sindri', 'Katras'],
    'Bokaro': ['Bokaro', 'Chas', 'Gomia', 'Bermo'],
    'Hazaribagh': ['Hazaribagh', 'Barhi', 'Ichak', 'Padma'],
    'Deoghar': ['Deoghar', 'Madhupur', 'Jasidih'],
    'Giridih': ['Giridih', 'Dumri', 'Bagodar', 'Bengabad'],
    'Dumka': ['Dumka', 'Saraiyahat', 'Jama', 'Masalia'],
  },
  'Karnataka': {
    'Bengaluru Urban': ['Bengaluru', 'Yelahanka', 'Anekal', 'Kengeri'],
    'Bengaluru Rural': ['Devanahalli', 'Doddaballapura', 'Hoskote', 'Nelamangala'],
    'Mysuru': ['Mysuru', 'Nanjangud', 'T Narasipura', 'Hunsur', 'Periyapatna'],
    'Belgaum': ['Belgaum', 'Athani', 'Bailhongal', 'Gokak', 'Ramdurg'],
    'Hubli-Dharwad': ['Hubli', 'Dharwad', 'Kalghatgi', 'Navalgund'],
    'Mangalore': ['Mangalore', 'Puttur', 'Bantwal', 'Sullia'],
    'Gulbarga': ['Gulbarga', 'Aland', 'Chincholi', 'Sedam', 'Afzalpur'],
    'Shimoga': ['Shimoga', 'Bhadravati', 'Sagar', 'Shikaripura'],
    'Tumkur': ['Tumkur', 'Tiptur', 'Madhugiri', 'Sira', 'Gubbi'],
    'Bellary': ['Bellary', 'Hospet', 'Sandur', 'Siruguppa'],
    'Raichur': ['Raichur', 'Sindhanur', 'Manvi', 'Lingasugur'],
    'Davangere': ['Davangere', 'Harihar', 'Jagalur', 'Channagiri'],
  },
  'Kerala': {
    'Thiruvananthapuram': ['Thiruvananthapuram', 'Neyyattinkara', 'Nedumangad', 'Attingal'],
    'Ernakulam': ['Kochi', 'Aluva', 'Angamaly', 'Perumbavoor', 'Kothamangalam'],
    'Kozhikode': ['Kozhikode', 'Vadakara', 'Koyilandy', 'Thamarassery'],
    'Thrissur': ['Thrissur', 'Chalakudy', 'Irinjalakuda', 'Kodungallur', 'Guruvayoor'],
    'Kollam': ['Kollam', 'Karunagappally', 'Punalur', 'Kottarakkara'],
    'Kannur': ['Kannur', 'Thalassery', 'Payyanur', 'Taliparamba'],
    'Alappuzha': ['Alappuzha', 'Cherthala', 'Kayamkulam', 'Haripad'],
    'Palakkad': ['Palakkad', 'Ottapalam', 'Mannarkkad', 'Chittur', 'Alathur'],
    'Malappuram': ['Malappuram', 'Manjeri', 'Perinthalmanna', 'Ponnani', 'Tirur'],
    'Kottayam': ['Kottayam', 'Changanassery', 'Pala', 'Ettumanoor'],
    'Idukki': ['Idukki', 'Thodupuzha', 'Adimali', 'Munnar'],
    'Pathanamthitta': ['Pathanamthitta', 'Adoor', 'Thiruvalla', 'Ranni'],
    'Wayanad': ['Kalpetta', 'Sulthan Bathery', 'Mananthavady'],
    'Kasaragod': ['Kasaragod', 'Kanhangad', 'Nileshwar'],
  },
  'Madhya Pradesh': {
    'Bhopal': ['Bhopal', 'Berasia', 'Sehore', 'Raisen'],
    'Indore': ['Indore', 'Depalpur', 'Mhow', 'Sanwer', 'Hatod'],
    'Jabalpur': ['Jabalpur', 'Panagar', 'Sihora', 'Katni', 'Patan'],
    'Gwalior': ['Gwalior', 'Dabra', 'Bhitarwar', 'Morar'],
    'Ujjain': ['Ujjain', 'Nagda', 'Mahidpur', 'Tarana'],
    'Sagar': ['Sagar', 'Bina', 'Khurai', 'Banda', 'Rehli'],
    'Satna': ['Satna', 'Maihar', 'Amarpatan'],
    'Rewa': ['Rewa', 'Sirmour', 'Mauganj', 'Hanumana'],
    'Dewas': ['Dewas', 'Sonkatch', 'Bagli', 'Kannod'],
    'Vidisha': ['Vidisha', 'Ganj Basoda', 'Nateran'],
    'Chhindwara': ['Chhindwara', 'Pandhurna', 'Sausar', 'Amarwara'],
    'Ratlam': ['Ratlam', 'Jaora', 'Alot', 'Sailana'],
    'Hoshangabad': ['Hoshangabad', 'Itarsi', 'Pipariya', 'Babai', 'Sohagpur'],
    'Mandsaur': ['Mandsaur', 'Neemuch', 'Garoth'],
    'Morena': ['Morena', 'Ambah', 'Porsa', 'Sabalgarh'],
  },
  'Maharashtra': {
    'Mumbai': ['Mumbai', 'Andheri', 'Borivali', 'Kurla', 'Dadar', 'Bandra'],
    'Pune': ['Pune', 'Baramati', 'Junnar', 'Indapur', 'Shirur', 'Maval', 'Bhor', 'Daund'],
    'Nashik': ['Nashik', 'Sinnar', 'Dindori', 'Malegaon', 'Igatpuri', 'Niphad'],
    'Nagpur': ['Nagpur', 'Kamptee', 'Hingna', 'Saoner', 'Umred', 'Katol'],
    'Aurangabad': ['Aurangabad', 'Paithan', 'Gangapur', 'Khuldabad', 'Vaijapur'],
    'Solapur': ['Solapur', 'Pandharpur', 'Akkalkot', 'Barshi', 'Karmala'],
    'Kolhapur': ['Kolhapur', 'Ichalkaranji', 'Gadhinglaj', 'Kagal', 'Panhala'],
    'Ahmednagar': ['Ahmednagar', 'Shrirampur', 'Sangamner', 'Kopargaon', 'Rahuri'],
    'Satara': ['Satara', 'Karad', 'Wai', 'Phaltan', 'Mahabaleshwar'],
    'Sangli': ['Sangli', 'Miraj', 'Vita', 'Tasgaon', 'Islampur'],
    'Jalgaon': ['Jalgaon', 'Bhusawal', 'Amalner', 'Chopda', 'Pachora'],
    'Latur': ['Latur', 'Udgir', 'Ausa', 'Nilanga', 'Ahmedpur'],
    'Thane': ['Thane', 'Kalyan', 'Bhiwandi', 'Ambarnath', 'Ulhasnagar'],
    'Raigad': ['Alibaug', 'Panvel', 'Pen', 'Karjat', 'Mangaon'],
    'Amravati': ['Amravati', 'Achalpur', 'Morshi', 'Warud'],
    'Nanded': ['Nanded', 'Deglur', 'Mukhed', 'Kinwat'],
    'Beed': ['Beed', 'Ambejogai', 'Georai', 'Parli'],
    'Osmanabad': ['Osmanabad', 'Tuljapur', 'Omerga', 'Paranda'],
    'Ratnagiri': ['Ratnagiri', 'Chiplun', 'Dapoli', 'Guhagar'],
  },
  'Odisha': {
    'Bhubaneswar': ['Bhubaneswar', 'Jatni', 'Pipili', 'Balipatna'],
    'Cuttack': ['Cuttack', 'Choudwar', 'Banki', 'Athagarh'],
    'Balasore': ['Balasore', 'Jaleswar', 'Soro', 'Basta'],
    'Sambalpur': ['Sambalpur', 'Burla', 'Hirakud'],
    'Berhampur': ['Berhampur', 'Chhatrapur', 'Aska'],
    'Puri': ['Puri', 'Konark', 'Nimapara'],
    'Rourkela': ['Rourkela', 'Rajgangpur', 'Panposh'],
    'Koraput': ['Koraput', 'Jeypore', 'Sunabeda'],
    'Mayurbhanj': ['Baripada', 'Rairangpur', 'Karanjia'],
  },
  'Punjab': {
    'Amritsar': ['Amritsar', 'Ajnala', 'Attari', 'Baba Bakala', 'Majitha'],
    'Ludhiana': ['Ludhiana', 'Jagraon', 'Khanna', 'Raikot', 'Samrala'],
    'Patiala': ['Patiala', 'Rajpura', 'Nabha', 'Samana', 'Patran'],
    'Jalandhar': ['Jalandhar', 'Phagwara', 'Nakodar', 'Shahkot', 'Kartarpur'],
    'Bathinda': ['Bathinda', 'Rampura Phul', 'Talwandi Sabo', 'Maur'],
    'Mohali': ['Mohali', 'Kharar', 'Derabassi', 'Lalru'],
    'Hoshiarpur': ['Hoshiarpur', 'Dasuya', 'Garhshankar', 'Mukerian', 'Tanda'],
    'Sangrur': ['Sangrur', 'Malerkotla', 'Sunam', 'Dhuri', 'Ahmedgarh'],
    'Moga': ['Moga', 'Nihal Singh Wala', 'Baghapurana', 'Dharamkot'],
    'Ferozepur': ['Ferozepur', 'Fazilka', 'Zira', 'Jalalabad'],
    'Pathankot': ['Pathankot', 'Dhar Kalan', 'Sujanpur'],
    'Kapurthala': ['Kapurthala', 'Sultanpur Lodhi', 'Bholath'],
    'Barnala': ['Barnala', 'Tapa', 'Mehal Kalan'],
    'Muktsar': ['Muktsar', 'Malout', 'Gidderbaha'],
    'Rupnagar': ['Rupnagar', 'Anandpur Sahib', 'Morinda'],
    'Faridkot': ['Faridkot', 'Kotkapura', 'Jaitu'],
    'Mansa': ['Mansa', 'Budhlada', 'Sardulgarh'],
    'Gurdaspur': ['Gurdaspur', 'Batala', 'Dera Baba Nanak', 'Qadian'],
  },
  'Rajasthan': {
    'Jaipur': ['Jaipur', 'Amber', 'Sanganer', 'Chomu', 'Bassi', 'Shahpura'],
    'Jodhpur': ['Jodhpur', 'Phalodi', 'Bilara', 'Pipar'],
    'Udaipur': ['Udaipur', 'Salumbar', 'Mavli', 'Rajsamand', 'Nathdwara'],
    'Kota': ['Kota', 'Ramganj Mandi', 'Sangod'],
    'Ajmer': ['Ajmer', 'Kishangarh', 'Beawar', 'Nasirabad', 'Pushkar'],
    'Bikaner': ['Bikaner', 'Nokha', 'Lunkaransar'],
    'Alwar': ['Alwar', 'Behror', 'Tijara', 'Rajgarh'],
    'Bhilwara': ['Bhilwara', 'Shahpura', 'Mandal', 'Gangapur'],
    'Sikar': ['Sikar', 'Lachhmangarh', 'Fatehpur', 'Neem Ka Thana'],
    'Pali': ['Pali', 'Marwar Junction', 'Sojat', 'Jaitaran'],
    'Sri Ganganagar': ['Sri Ganganagar', 'Suratgarh', 'Anupgarh'],
    'Nagaur': ['Nagaur', 'Makrana', 'Didwana', 'Degana'],
    'Jhunjhunu': ['Jhunjhunu', 'Nawalgarh', 'Mandawa', 'Chirawa'],
    'Churu': ['Churu', 'Ratangarh', 'Rajgarh', 'Sardarshahar'],
    'Tonk': ['Tonk', 'Niwai', 'Malpura', 'Deoli'],
    'Barmer': ['Barmer', 'Balotra', 'Siwana'],
    'Jaisalmer': ['Jaisalmer', 'Pokhran', 'Sam'],
    'Hanumangarh': ['Hanumangarh', 'Nohar', 'Pilibanga'],
    'Dausa': ['Dausa', 'Lalsot', 'Bandikui'],
    'Sawai Madhopur': ['Sawai Madhopur', 'Gangapur', 'Bonli'],
  },
  'Tamil Nadu': {
    'Chennai': ['Chennai', 'Tambaram', 'Avadi', 'Ambattur', 'Sholinganallur'],
    'Coimbatore': ['Coimbatore', 'Mettupalayam', 'Pollachi', 'Annur', 'Sulur'],
    'Madurai': ['Madurai', 'Melur', 'Vadipatti', 'Thirumangalam'],
    'Tiruchirappalli': ['Tiruchirappalli', 'Srirangam', 'Lalgudi', 'Musiri'],
    'Salem': ['Salem', 'Attur', 'Mettur', 'Omalur', 'Sankari'],
    'Tirunelveli': ['Tirunelveli', 'Palayamkottai', 'Ambasamudram', 'Tenkasi'],
    'Erode': ['Erode', 'Bhavani', 'Gobichettipalayam', 'Perundurai'],
    'Vellore': ['Vellore', 'Ambur', 'Vaniyambadi', 'Gudiyatham'],
    'Thanjavur': ['Thanjavur', 'Kumbakonam', 'Pattukottai', 'Orathanadu'],
    'Dindigul': ['Dindigul', 'Palani', 'Oddanchatram', 'Natham'],
    'Krishnagiri': ['Krishnagiri', 'Hosur', 'Denkanikottai'],
    'Tuticorin': ['Tuticorin', 'Tiruchendur', 'Kovilpatti'],
    'Cuddalore': ['Cuddalore', 'Chidambaram', 'Virudhachalam'],
    'Kanchipuram': ['Kanchipuram', 'Sriperumbudur', 'Uthiramerur'],
    'Tiruvannamalai': ['Tiruvannamalai', 'Arani', 'Polur', 'Chengam'],
    'Namakkal': ['Namakkal', 'Rasipuram', 'Tiruchengode'],
  },
  'Telangana': {
    'Hyderabad': ['Hyderabad', 'Secunderabad', 'Kukatpally', 'Uppal', 'LB Nagar'],
    'Rangareddy': ['Shamshabad', 'Chevella', 'Ibrahimpatnam'],
    'Warangal': ['Warangal', 'Hanamkonda', 'Jangaon'],
    'Karimnagar': ['Karimnagar', 'Huzurabad', 'Jagtial', 'Peddapalli'],
    'Nizamabad': ['Nizamabad', 'Bodhan', 'Armoor', 'Kamareddy'],
    'Khammam': ['Khammam', 'Kothagudem', 'Bhadrachalam'],
    'Nalgonda': ['Nalgonda', 'Miryalaguda', 'Suryapet', 'Bhongir'],
    'Mahbubnagar': ['Mahbubnagar', 'Jadcherla', 'Narayanpet', 'Wanaparthy'],
    'Adilabad': ['Adilabad', 'Nirmal', 'Mancherial'],
    'Medak': ['Sangareddy', 'Medak', 'Siddipet', 'Zaheerabad'],
  },
  'Uttar Pradesh': {
    'Lucknow': ['Lucknow', 'Bakshi Ka Talab', 'Malihabad', 'Mohanlalganj'],
    'Agra': ['Agra', 'Fatehpur Sikri', 'Firozabad', 'Tundla', 'Shamsabad'],
    'Varanasi': ['Varanasi', 'Pindra', 'Rohaniya', 'Cholapur', 'Sevapuri'],
    'Kanpur Nagar': ['Kanpur', 'Bilhaur', 'Ghatampur', 'Bhitargaon'],
    'Prayagraj': ['Prayagraj', 'Phulpur', 'Soraon', 'Handia', 'Meja'],
    'Gorakhpur': ['Gorakhpur', 'Sahjanwa', 'Chauri Chaura', 'Khajni'],
    'Meerut': ['Meerut', 'Sardhana', 'Mawana', 'Hastinapur'],
    'Bareilly': ['Bareilly', 'Baheri', 'Meerganj', 'Nawabganj'],
    'Aligarh': ['Aligarh', 'Atrauli', 'Iglas', 'Khair'],
    'Moradabad': ['Moradabad', 'Sambhal', 'Chandausi', 'Bilari'],
    'Saharanpur': ['Saharanpur', 'Deoband', 'Nakur', 'Behat'],
    'Mathura': ['Mathura', 'Vrindavan', 'Chhata', 'Baldeo', 'Govardhan'],
    'Jhansi': ['Jhansi', 'Lalitpur', 'Babina', 'Moth'],
    'Azamgarh': ['Azamgarh', 'Mau', 'Ballia', 'Mubarakpur'],
    'Sultanpur': ['Sultanpur', 'Amethi', 'Musafirkhana', 'Kadipur'],
    'Jaunpur': ['Jaunpur', 'Shahganj', 'Machhalishahar', 'Mariahu'],
    'Faizabad': ['Faizabad', 'Ayodhya', 'Tanda', 'Sohawal'],
    'Mirzapur': ['Mirzapur', 'Chunar', 'Ahraura', 'Lalganj'],
    'Basti': ['Basti', 'Khalilabad', 'Harraiya'],
    'Ghaziabad': ['Ghaziabad', 'Loni', 'Muradnagar', 'Modinagar'],
    'Gautam Buddha Nagar': ['Noida', 'Greater Noida', 'Dadri', 'Jewar'],
    'Chandauli': ['Chandauli', 'Chakia', 'Mughalsarai', 'Sakaldiha', 'Naugarh'],
    'Sonbhadra': ['Sonbhadra', 'Robertsganj', 'Churk', 'Chopan'],
    'Gonda': ['Gonda', 'Colonelganj', 'Katra Bazar', 'Mankapur'],
    'Deoria': ['Deoria', 'Salempur', 'Bhatpar Rani', 'Padrauna'],
    'Pratapgarh': ['Pratapgarh', 'Kunda', 'Patti'],
    'Rae Bareli': ['Rae Bareli', 'Lalganj', 'Salon', 'Dalmau'],
    'Unnao': ['Unnao', 'Hasanganj', 'Purwa', 'Safipur'],
    'Hardoi': ['Hardoi', 'Shahabad', 'Sandila', 'Bilgram'],
    'Sitapur': ['Sitapur', 'Biswan', 'Misrikh', 'Mahmoodabad'],
    'Lakhimpur Kheri': ['Lakhimpur', 'Gola Gokarannath', 'Mohammadi'],
    'Shahjahanpur': ['Shahjahanpur', 'Tilhar', 'Powayan'],
    'Rampur': ['Rampur', 'Bilaspur', 'Swar', 'Tanda'],
    'Muzaffarnagar': ['Muzaffarnagar', 'Shamli', 'Kairana'],
    'Bijnor': ['Bijnor', 'Nagina', 'Najibabad', 'Dhampur'],
    'Etawah': ['Etawah', 'Bharthana', 'Jaswantnagar'],
    'Mainpuri': ['Mainpuri', 'Bhogaon', 'Shikohabad'],
    'Budaun': ['Budaun', 'Bilsi', 'Sahaswan', 'Dataganj'],
    'Banda': ['Banda', 'Baberu', 'Naraini', 'Atarra'],
    'Fatehpur': ['Fatehpur', 'Bindki', 'Khaga'],
    'Barabanki': ['Barabanki', 'Nawabganj', 'Fatehpur', 'Haidergarh'],
    'Bulandshahr': ['Bulandshahr', 'Khurja', 'Sikandrabad', 'Anupshahar'],
    'Hapur': ['Hapur', 'Pilkhuwa', 'Garhmukteshwar'],
    'Pilibhit': ['Pilibhit', 'Bisalpur', 'Puranpur'],
    'Firozabad': ['Firozabad', 'Tundla', 'Shikohabad'],
    'Hathras': ['Hathras', 'Sadabad', 'Sikandra Rao'],
  },
  'Uttarakhand': {
    'Dehradun': ['Dehradun', 'Mussoorie', 'Rishikesh', 'Vikasnagar', 'Doiwala'],
    'Haridwar': ['Haridwar', 'Roorkee', 'Laksar', 'Jwalapur'],
    'Nainital': ['Haldwani', 'Nainital', 'Ramnagar', 'Bhimtal'],
    'Udham Singh Nagar': ['Rudrapur', 'Kashipur', 'Kichha', 'Sitarganj'],
    'Almora': ['Almora', 'Ranikhet', 'Bhikiyasain'],
    'Pauri Garhwal': ['Pauri', 'Kotdwar', 'Lansdowne'],
    'Tehri Garhwal': ['New Tehri', 'Chamba', 'Narendra Nagar'],
    'Pithoragarh': ['Pithoragarh', 'Champawat', 'Lohaghat'],
  },
  'West Bengal': {
    'Kolkata': ['Kolkata', 'Salt Lake', 'Dum Dum', 'Behala', 'Jadavpur'],
    'Howrah': ['Howrah', 'Shibpur', 'Uluberia', 'Amta'],
    'North 24 Parganas': ['Barasat', 'Basirhat', 'Bongaon', 'Habra', 'Barrackpore'],
    'South 24 Parganas': ['Baruipur', 'Diamond Harbour', 'Canning', 'Sonarpur'],
    'Hooghly': ['Hooghly', 'Chinsurah', 'Serampore', 'Arambagh'],
    'Burdwan': ['Burdwan', 'Durgapur', 'Asansol', 'Kalna'],
    'Murshidabad': ['Berhampore', 'Jangipur', 'Lalbag', 'Domkal'],
    'Nadia': ['Krishnanagar', 'Nabadwip', 'Ranaghat', 'Shantipur'],
    'Midnapore': ['Midnapore', 'Kharagpur', 'Jhargram', 'Ghatal'],
    'Bankura': ['Bankura', 'Bishnupur', 'Sonamukhi'],
    'Birbhum': ['Suri', 'Bolpur', 'Rampurhat', 'Sainthia'],
    'Malda': ['Malda', 'Old Malda', 'Gazole'],
    'Jalpaiguri': ['Jalpaiguri', 'Alipurduar', 'Siliguri'],
    'Darjeeling': ['Darjeeling', 'Siliguri', 'Kurseong', 'Kalimpong'],
    'Cooch Behar': ['Cooch Behar', 'Dinhata', 'Tufanganj'],
    'Purulia': ['Purulia', 'Raghunathpur', 'Jhalda'],
  },
};

export const locationStates = Object.keys(locationOptions);

export const getDistricts = (state) => (
  state && locationOptions[state] ? Object.keys(locationOptions[state]) : []
);

export const getVillages = (state, district) => (
  state && district && locationOptions[state]?.[district]
    ? locationOptions[state][district]
    : []
);

export const isValidLocation = ({ state, district, village }) => (
  locationStates.includes(state)
  && getDistricts(state).includes(district)
  && getVillages(state, district).includes(village)
);