export const mockCrops = [
  { id: 1, name: 'Wheat', nameHi: 'गेहूं', nameMr: 'गहू', namePa: 'ਕਣਕ', category: 'Cereal', icon: '🌾', basePrice: 2200 },
  { id: 2, name: 'Paddy', nameHi: 'धान', nameMr: 'भात', namePa: 'ਝੋਨਾ', category: 'Cereal', icon: '🌾', basePrice: 2300 },
  { id: 3, name: 'Maize', nameHi: 'मक्का', nameMr: 'मका', namePa: 'ਮੱਕੀ', category: 'Cereal', icon: '🌽', basePrice: 2100 },
  { id: 4, name: 'Mustard', nameHi: 'सरसों', nameMr: 'मोहरी', namePa: 'ਸਰ੍ਹੋਂ', category: 'Oilseed', icon: '🌼', basePrice: 5650 },
  { id: 5, name: 'Chickpea', nameHi: 'चना', nameMr: 'हरभरा', namePa: 'ਛੋਲੇ', category: 'Pulse', icon: '🟤', basePrice: 5440 },
  { id: 6, name: 'Onion', nameHi: 'प्याज', nameMr: 'कांदा', namePa: 'ਪਿਆਜ਼', category: 'Vegetable', icon: '🧅', basePrice: 1800 },
  { id: 7, name: 'Potato', nameHi: 'आलू', nameMr: 'बटाटा', namePa: 'ਆਲੂ', category: 'Vegetable', icon: '🥔', basePrice: 1200 },
  { id: 8, name: 'Tomato', nameHi: 'टमाटर', nameMr: 'टोमॅटो', namePa: 'ਟਮਾਟਰ', category: 'Vegetable', icon: '🍅', basePrice: 2400 },
  { id: 9, name: 'Rice', nameHi: 'चावल', nameMr: 'तांदूळ', namePa: 'ਚਾਵਲ', category: 'Cereal', icon: '🌾', basePrice: 3100 },
  { id: 10, name: 'Soybean', nameHi: 'सोयाबीन', nameMr: 'सोयाबीन', namePa: 'ਸੋਇਆਬੀਨ', category: 'Oilseed', icon: '🟢', basePrice: 4300 },
  { id: 11, name: 'Cotton', nameHi: 'कपास', nameMr: 'कापूस', namePa: 'ਕਪਾਹ', category: 'Cash Crop', icon: '☁️', basePrice: 6200 },
  { id: 12, name: 'Sugarcane', nameHi: 'गन्ना', nameMr: 'ऊस', namePa: 'ਗੰਨਾ', category: 'Cash Crop', icon: '🎋', basePrice: 3150 },
];

export const mockBuyers = [
  {
    id: 1,
    name: 'Greater Noida Agro Traders',
    type: 'Wholesaler',
    cropRequired: 'Wheat',
    cropsWanted: ['Wheat', 'Paddy', 'Mustard'],
    pricePerQtl: 2310,
    quantityNeeded: 80,
    minimumQuantity: 20,
    maximumQuantity: 100,
    contact: '+91 98100 11101',
    whatsapp: true,
    location: 'Surajpur, Greater Noida',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    latitude: 28.5655,
    longitude: 77.3611,
    verified: true,
    verificationType: 'GST Verified',
    rating: 4.6,
    totalTransactions: 142,
    responseTime: 'Usually responds within 30 min',
    preferredPickup: 'Buyer pickup available',
    paymentTerms: 'Same-day payment',
    availability: 'Buying now',
    updatedAt: '1 hour ago',
    description: 'Established wholesale grain trader serving Greater Noida since 2012. Specialises in wheat, paddy and mustard procurement directly from farmers.',
  },
  {
    id: 2,
    name: 'Noida Mandi Traders',
    type: 'Mandi Buyer',
    cropRequired: 'Paddy',
    cropsWanted: ['Paddy', 'Wheat', 'Maize'],
    pricePerQtl: 2390,
    quantityNeeded: 200,
    minimumQuantity: 50,
    maximumQuantity: 500,
    contact: '+91 98100 11102',
    whatsapp: true,
    location: 'Sector 88, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    latitude: 28.5759,
    longitude: 77.3630,
    verified: true,
    verificationType: 'Mandi Licensed',
    rating: 4.4,
    totalTransactions: 289,
    responseTime: 'Responds within 1 hour',
    preferredPickup: 'Farmer delivery or buyer pickup',
    paymentTerms: 'Payment within 2 days',
    availability: 'Buying now',
    updatedAt: '2 hours ago',
    description: 'Licensed mandi buyer with warehousing at Sector 88, Noida. High-volume procurement for paddy, wheat and maize throughout the harvest season.',
  },
  {
    id: 3,
    name: 'Kisan Fresh Retail Network',
    type: 'Retailer',
    cropRequired: 'Wheat',
    cropsWanted: ['Wheat', 'Chickpea', 'Mustard'],
    pricePerQtl: 2450,
    quantityNeeded: 40,
    minimumQuantity: 10,
    maximumQuantity: 60,
    contact: '+91 98100 11103',
    whatsapp: true,
    location: 'Vaishali, Ghaziabad',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    latitude: 28.6448,
    longitude: 77.3481,
    verified: true,
    verificationType: 'FSSAI Registered',
    rating: 4.8,
    totalTransactions: 87,
    responseTime: 'Usually responds within 15 min',
    preferredPickup: 'Buyer arranges transport',
    paymentTerms: 'Instant payment on delivery',
    availability: 'Buying now',
    updatedAt: '30 min ago',
    description: 'Retail chain sourcing fresh farm produce directly from farmers. Premium prices for quality grain. FSSAI registered operation in NCR.',
  },
  {
    id: 4,
    name: 'Krishna Wholesale Foods',
    type: 'Wholesaler',
    cropRequired: 'Maize',
    cropsWanted: ['Maize', 'Paddy', 'Soybean'],
    pricePerQtl: 2190,
    quantityNeeded: 150,
    minimumQuantity: 30,
    maximumQuantity: 300,
    contact: '+91 98100 11104',
    whatsapp: false,
    location: 'Dadri, Gautam Buddha Nagar',
    city: 'Dadri',
    state: 'Uttar Pradesh',
    latitude: 28.5530,
    longitude: 77.5540,
    verified: true,
    verificationType: 'GST Verified',
    rating: 4.2,
    totalTransactions: 215,
    responseTime: 'Responds within 2 hours',
    preferredPickup: 'Farmer delivers to Dadri facility',
    paymentTerms: 'Payment in 3–5 days',
    availability: 'Buying now',
    updatedAt: 'today',
    description: 'Bulk wholesale food distributor specialising in maize and feed-grade grain. Supplies to poultry farms and food processing units across Western UP.',
  },
  {
    id: 5,
    name: 'Delhi Sabzi Mandi',
    type: 'Mandi Buyer',
    cropRequired: 'Mustard',
    cropsWanted: ['Mustard', 'Chickpea', 'Wheat'],
    pricePerQtl: 5880,
    quantityNeeded: 60,
    minimumQuantity: 15,
    maximumQuantity: 100,
    contact: '+91 98100 11105',
    whatsapp: true,
    location: 'Azadpur Mandi, Delhi',
    city: 'Delhi',
    state: 'Delhi',
    latitude: 28.7147,
    longitude: 77.1694,
    verified: true,
    verificationType: 'APMC Licensed',
    rating: 4.5,
    totalTransactions: 1240,
    responseTime: 'Responds within 45 min',
    preferredPickup: 'Farmer delivery preferred',
    paymentTerms: 'Same-day RTGS payment',
    availability: 'Buying now',
    updatedAt: 'just now',
    description: "One of Delhi's largest APMC-licensed mandi buyers. Direct procurement for mustard oil mills and chickpea processing. Trusted by hundreds of farmers.",
  },
  {
    id: 6,
    name: 'NCR Grain Distributors',
    type: 'Distributor',
    cropRequired: 'Wheat',
    cropsWanted: ['Wheat', 'Rice', 'Maize'],
    pricePerQtl: 2340,
    quantityNeeded: 300,
    minimumQuantity: 100,
    maximumQuantity: 600,
    contact: '+91 98100 11106',
    whatsapp: true,
    location: 'Greater Noida West',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    latitude: 28.6191,
    longitude: 77.4046,
    verified: false,
    verificationType: null,
    rating: 3.9,
    totalTransactions: 56,
    responseTime: 'Responds within 3 hours',
    preferredPickup: 'Flexible — pickup or delivery',
    paymentTerms: 'Weekly payment cycle',
    availability: 'Currently buying',
    updatedAt: 'yesterday',
    description: 'Regional distributor supplying retail chains and modern trade partners in Delhi-NCR. Looking to expand direct farmer partnerships.',
  },
  {
    id: 7,
    name: 'UP Govt. Procurement Centre',
    type: 'Govt Agency',
    cropRequired: 'Wheat',
    cropsWanted: ['Wheat', 'Paddy', 'Mustard'],
    pricePerQtl: 2275,
    quantityNeeded: 1000,
    minimumQuantity: 20,
    maximumQuantity: 5000,
    contact: '+91 98100 11107',
    whatsapp: false,
    location: 'Surajpur, Greater Noida',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    latitude: 28.5711,
    longitude: 77.3718,
    verified: true,
    verificationType: 'Government Agency',
    rating: 4.1,
    totalTransactions: 5800,
    responseTime: '1 business day',
    preferredPickup: 'Farmer delivers to procurement centre',
    paymentTerms: 'Government DBT — payment in 7 days',
    availability: 'Open for procurement',
    updatedAt: 'today',
    description: 'Official UP government procurement centre under MSP guidelines. Registered farmers receive guaranteed minimum support price. Kisan registration required.',
  },
  {
    id: 8,
    name: 'Bulandshahr Agro Trade',
    type: 'Wholesaler',
    cropRequired: 'Chickpea',
    cropsWanted: ['Chickpea', 'Mustard', 'Paddy'],
    pricePerQtl: 5620,
    quantityNeeded: 80,
    minimumQuantity: 20,
    maximumQuantity: 150,
    contact: '+91 98100 11108',
    whatsapp: true,
    location: 'Bulandshahr, UP',
    city: 'Bulandshahr',
    state: 'Uttar Pradesh',
    latitude: 28.4069,
    longitude: 77.8500,
    verified: false,
    verificationType: null,
    rating: 4.0,
    totalTransactions: 98,
    responseTime: 'Responds within 2 hours',
    preferredPickup: 'Buyer sends vehicle',
    paymentTerms: 'Payment within 3 days',
    availability: 'Actively buying',
    updatedAt: '3 hours ago',
    description: 'Active pulse trader across Bulandshahr and Aligarh belt. Purchasing chickpea and mustard for supply to national dal mills and oil processing units.',
  },
  {
    id: 9,
    name: 'Hapur Fresh Market',
    type: 'Retailer',
    cropRequired: 'Paddy',
    cropsWanted: ['Paddy', 'Maize', 'Wheat'],
    pricePerQtl: 2420,
    quantityNeeded: 50,
    minimumQuantity: 10,
    maximumQuantity: 80,
    contact: '+91 98100 11109',
    whatsapp: true,
    location: 'Hapur, UP',
    city: 'Hapur',
    state: 'Uttar Pradesh',
    latitude: 28.7293,
    longitude: 77.7757,
    verified: true,
    verificationType: 'FSSAI Registered',
    rating: 4.3,
    totalTransactions: 62,
    responseTime: 'Usually responds within 1 hour',
    preferredPickup: 'Buyer pickup available',
    paymentTerms: 'Same-day cash or UPI',
    availability: 'Buying now',
    updatedAt: '4 hours ago',
    description: 'Local fresh market retailer sourcing paddy and maize directly from UP farmers. Preference for Grade-A paddy. Flexible on quantities with fast payment.',
  },
  {
    id: 10,
    name: 'Swaraj Agri Distributors',
    type: 'Distributor',
    cropRequired: 'Mustard',
    cropsWanted: ['Mustard', 'Soybean', 'Chickpea'],
    pricePerQtl: 5790,
    quantityNeeded: 100,
    minimumQuantity: 25,
    maximumQuantity: 200,
    contact: '+91 98100 11110',
    whatsapp: true,
    location: 'Loni, Ghaziabad',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    latitude: 28.7378,
    longitude: 77.2935,
    verified: true,
    verificationType: 'GST Verified',
    rating: 4.5,
    totalTransactions: 178,
    responseTime: 'Responds within 30 min',
    preferredPickup: 'Buyer arranges transport',
    paymentTerms: 'Instant payment on delivery',
    availability: 'Actively buying',
    updatedAt: '1 hour ago',
    description: 'Oilseed distributor supplying cold-pressed oil manufacturers in Delhi-NCR. High-price buyer for good-quality mustard. Trusted by 100+ farmers in Western UP.',
  },
];

export const mockPriceHistory = [
  {
    cropId: 1,
    mandi: 'Karnal Mandi',
    wholesale: 2260,
    retail: 2940,
    msp: 2200,
    date: '2026-08-01',
  },
  {
    cropId: 2,
    mandi: 'Ludhiana Mandi',
    wholesale: 2350,
    retail: 3100,
    msp: 2300,
    date: '2026-08-03',
  },
  {
    cropId: 3,
    mandi: 'Indore Mandi',
    wholesale: 2140,
    retail: 2780,
    msp: 2100,
    date: '2026-08-05',
  },
  {
    cropId: 4,
    mandi: 'Jaipur Mandi',
    wholesale: 5780,
    retail: 6950,
    msp: 5650,
    date: '2026-08-07',
  },
  {
    cropId: 5,
    mandi: 'Bhopal Mandi',
    wholesale: 5520,
    retail: 6700,
    msp: 5440,
    date: '2026-08-10',
  },
];

export const mockSupplyChain = [
  {
    cropId: 1,

    farmerCost: 2100,
    farmerLocation: 'Raghunath Pur, Chakia, Chandauli',
    farmQuantity: '20 Quintal',

    mandiName: 'Chakia Mandi',
    mandiPrice: 2150,
    mandiDistance: 8,

    wholesalerName: 'Sharma Grain Traders',
    wholesalerLocation: 'Chakia Mandi, Chandauli',
    wholesalerCost: 2260,
    wholesalerDistance: 8,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 50 Quintal',
    wholesalerActiveCount: 12,
    wholesalerAvgPrice: 2240,
    wholesalerBestPrice: 2280,
    wholesalerLowestPrice: 2200,

    distributorName: 'Eastern Grain Supply',
    distributorLocation: 'Varanasi',
    distributorCost: 2490,
    distributorSelling: 2550,
    distributorDistance: 72,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '2–4 hours',

    retailerName: 'Local Grain Store',
    retailerType: 'Grain & Grocery Shop',
    retailerLocation: 'Varanasi City',
    retailerCost: 2700,
    consumerPrice: 2940,
    retailerMarket: 'Local Consumer Market',

    transportCost: 120,
    distance: 80,
  },
  {
    cropId: 2,
    farmerCost: 1950,
    farmerLocation: 'Ludhiana Rural, Punjab',
    farmQuantity: '30 Quintal',
    mandiName: 'Ludhiana Mandi',
    mandiPrice: 2050,
    mandiDistance: 15,
    wholesalerName: 'Punjab Rice Traders',
    wholesalerLocation: 'Ludhiana Mandi',
    wholesalerCost: 2350,
    wholesalerDistance: 15,
    wholesalerTransport: 'Buyer-arranged',
    wholesalerQuantityAccepted: 'Up to 80 Quintal',
    wholesalerActiveCount: 8,
    wholesalerAvgPrice: 2320,
    wholesalerBestPrice: 2370,
    wholesalerLowestPrice: 2280,
    distributorName: 'North India Grain Co.',
    distributorLocation: 'Chandigarh',
    distributorCost: 2620,
    distributorSelling: 2700,
    distributorDistance: 90,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '3–5 hours',
    retailerName: 'Local Provisions Store',
    retailerType: 'Grocery & Grain Shop',
    retailerLocation: 'Chandigarh City',
    retailerCost: 2880,
    consumerPrice: 3100,
    retailerMarket: 'Urban Consumer Market',
    transportCost: 135,
    distance: 42,
  },
  {
    cropId: 3,
    farmerCost: 1720,
    farmerLocation: 'Harda District, Madhya Pradesh',
    farmQuantity: '25 Quintal',
    mandiName: 'Indore Mandi',
    mandiPrice: 1850,
    mandiDistance: 12,
    wholesalerName: 'Kisan Agro Foods',
    wholesalerLocation: 'Indore Mandi, MP',
    wholesalerCost: 2140,
    wholesalerDistance: 12,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 60 Quintal',
    wholesalerActiveCount: 6,
    wholesalerAvgPrice: 2120,
    wholesalerBestPrice: 2175,
    wholesalerLowestPrice: 2060,
    distributorName: 'Central India Grain Depot',
    distributorLocation: 'Bhopal',
    distributorCost: 2370,
    distributorSelling: 2450,
    distributorDistance: 65,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '2–3 hours',
    retailerName: 'Bhopal Grocery Hub',
    retailerType: 'Retail Grocery',
    retailerLocation: 'Bhopal City',
    retailerCost: 2550,
    consumerPrice: 2780,
    retailerMarket: 'Local Consumer Market',
    transportCost: 105,
    distance: 28,
  },
  {
    cropId: 4,
    farmerCost: 4900,
    farmerLocation: 'Bharatpur, Rajasthan',
    farmQuantity: '15 Quintal',
    mandiName: 'Jaipur Mandi',
    mandiPrice: 5200,
    mandiDistance: 20,
    wholesalerName: 'Rajasthan Oil Seeds Traders',
    wholesalerLocation: 'Jaipur Mandi, Rajasthan',
    wholesalerCost: 5780,
    wholesalerDistance: 20,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 30 Quintal',
    wholesalerActiveCount: 5,
    wholesalerAvgPrice: 5720,
    wholesalerBestPrice: 5850,
    wholesalerLowestPrice: 5600,
    distributorName: 'Western India Oil Distribution',
    distributorLocation: 'Jodhpur',
    distributorCost: 6200,
    distributorSelling: 6400,
    distributorDistance: 120,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '4–6 hours',
    retailerName: 'Green Leaf Stores',
    retailerType: 'Oil & Grocery Store',
    retailerLocation: 'Jodhpur City',
    retailerCost: 6550,
    consumerPrice: 6950,
    retailerMarket: 'Local & Urban Consumer Market',
    transportCost: 180,
    distance: 50,
  },
  {
    cropId: 5,
    farmerCost: 4680,
    farmerLocation: 'Vidisha District, Madhya Pradesh',
    farmQuantity: '18 Quintal',
    mandiName: 'Bhopal Mandi',
    mandiPrice: 5000,
    mandiDistance: 18,
    wholesalerName: 'Bharat Pulses Depot',
    wholesalerLocation: 'Bhopal Mandi, MP',
    wholesalerCost: 5520,
    wholesalerDistance: 18,
    wholesalerTransport: 'Buyer-arranged',
    wholesalerQuantityAccepted: 'Up to 40 Quintal',
    wholesalerActiveCount: 7,
    wholesalerAvgPrice: 5490,
    wholesalerBestPrice: 5580,
    wholesalerLowestPrice: 5400,
    distributorName: 'Central Pulses Logistics',
    distributorLocation: 'Nagpur',
    distributorCost: 5900,
    distributorSelling: 6050,
    distributorDistance: 85,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '3–4 hours',
    retailerName: 'Nagpur Provision Store',
    retailerType: 'Pulses & Grocery Store',
    retailerLocation: 'Nagpur City',
    retailerCost: 6300,
    consumerPrice: 6700,
    retailerMarket: 'Local Consumer Market',
    transportCost: 150,
    distance: 40,
  },
  {
    cropId: 6,
    farmerCost: 1200,
    farmerLocation: 'Niphad, Nashik, Maharashtra',
    farmQuantity: '40 Quintal',
    mandiName: 'Lasalgaon Mandi',
    mandiPrice: 1400,
    mandiDistance: 10,
    wholesalerName: 'Maharashtra Onion Traders',
    wholesalerLocation: 'Lasalgaon, Nashik',
    wholesalerCost: 1850,
    wholesalerDistance: 10,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 100 Quintal',
    wholesalerActiveCount: 18,
    wholesalerAvgPrice: 1800,
    wholesalerBestPrice: 1900,
    wholesalerLowestPrice: 1700,
    distributorName: 'Western India Agri Logistics',
    distributorLocation: 'Pune',
    distributorCost: 2200,
    distributorSelling: 2400,
    distributorDistance: 180,
    distributorTransportMode: 'Road (Cold Chain)',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '5–7 hours',
    retailerName: 'Pune Vegetable Market',
    retailerType: 'Vegetable & Grocery Store',
    retailerLocation: 'Pune City',
    retailerCost: 2600,
    consumerPrice: 3000,
    retailerMarket: 'Urban Consumer Market',
    transportCost: 200,
    distance: 190,
  },
  {
    cropId: 7,
    farmerCost: 800,
    farmerLocation: 'Farrukhabad, Uttar Pradesh',
    farmQuantity: '50 Quintal',
    mandiName: 'Agra Mandi',
    mandiPrice: 950,
    mandiDistance: 8,
    wholesalerName: 'UP Cold Storage Traders',
    wholesalerLocation: 'Agra Mandi, UP',
    wholesalerCost: 1250,
    wholesalerDistance: 8,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 120 Quintal',
    wholesalerActiveCount: 14,
    wholesalerAvgPrice: 1200,
    wholesalerBestPrice: 1280,
    wholesalerLowestPrice: 1100,
    distributorName: 'North India Food Distributors',
    distributorLocation: 'Delhi',
    distributorCost: 1600,
    distributorSelling: 1750,
    distributorDistance: 240,
    distributorTransportMode: 'Road (Truck)',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '5–8 hours',
    retailerName: 'Delhi Vegetable Market',
    retailerType: 'Vegetable & Kirana Store',
    retailerLocation: 'Delhi NCR',
    retailerCost: 1900,
    consumerPrice: 2200,
    retailerMarket: 'Urban Consumer Market',
    transportCost: 160,
    distance: 248,
  },
  {
    cropId: 8,
    farmerCost: 1500,
    farmerLocation: 'Narayangaon, Pune, Maharashtra',
    farmQuantity: '20 Quintal',
    mandiName: 'Nashik Mandi',
    mandiPrice: 1800,
    mandiDistance: 12,
    wholesalerName: 'Nashik Fresh Produce Traders',
    wholesalerLocation: 'Nashik Mandi',
    wholesalerCost: 2400,
    wholesalerDistance: 12,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 50 Quintal',
    wholesalerActiveCount: 10,
    wholesalerAvgPrice: 2350,
    wholesalerBestPrice: 2500,
    wholesalerLowestPrice: 2200,
    distributorName: 'Mumbai Fresh Supply Co.',
    distributorLocation: 'Mumbai',
    distributorCost: 3000,
    distributorSelling: 3500,
    distributorDistance: 200,
    distributorTransportMode: 'Road (Refrigerated)',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '4–6 hours',
    retailerName: 'Mumbai Sabzi Market',
    retailerType: 'Fresh Produce Market',
    retailerLocation: 'Mumbai City',
    retailerCost: 3800,
    consumerPrice: 4500,
    retailerMarket: 'Urban & Premium Consumer Market',
    transportCost: 220,
    distance: 212,
  },
  {
    cropId: 9,
    farmerCost: 2400,
    farmerLocation: 'West Bengal (Hooghly)',
    farmQuantity: '35 Quintal',
    mandiName: 'Burdwan Mandi',
    mandiPrice: 2650,
    mandiDistance: 20,
    wholesalerName: 'Bengal Rice Traders Assoc.',
    wholesalerLocation: 'Burdwan Mandi, WB',
    wholesalerCost: 3100,
    wholesalerDistance: 20,
    wholesalerTransport: 'Buyer-arranged',
    wholesalerQuantityAccepted: 'Up to 100 Quintal',
    wholesalerActiveCount: 9,
    wholesalerAvgPrice: 3050,
    wholesalerBestPrice: 3200,
    wholesalerLowestPrice: 2950,
    distributorName: 'Eastern India Grain Logistics',
    distributorLocation: 'Kolkata',
    distributorCost: 3500,
    distributorSelling: 3700,
    distributorDistance: 95,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '2–3 hours',
    retailerName: 'Kolkata Provisions Store',
    retailerType: 'Rice & Grocery Store',
    retailerLocation: 'Kolkata City',
    retailerCost: 4000,
    consumerPrice: 4500,
    retailerMarket: 'Urban Consumer Market',
    transportCost: 145,
    distance: 115,
  },
  {
    cropId: 10,
    farmerCost: 3800,
    farmerLocation: 'Latur, Maharashtra',
    farmQuantity: '25 Quintal',
    mandiName: 'Latur Mandi',
    mandiPrice: 4000,
    mandiDistance: 10,
    wholesalerName: 'Maharashtra Soybean Traders',
    wholesalerLocation: 'Latur Mandi, MH',
    wholesalerCost: 4300,
    wholesalerDistance: 10,
    wholesalerTransport: 'Farmer-arranged',
    wholesalerQuantityAccepted: 'Up to 50 Quintal',
    wholesalerActiveCount: 6,
    wholesalerAvgPrice: 4250,
    wholesalerBestPrice: 4350,
    wholesalerLowestPrice: 4150,
    distributorName: 'Vidarbha Oil Seeds Distribution',
    distributorLocation: 'Nagpur',
    distributorCost: 4700,
    distributorSelling: 4900,
    distributorDistance: 180,
    distributorTransportMode: 'Road',
    distributorTransportPayer: 'Distributor',
    distributorEstHours: '4–5 hours',
    retailerName: 'Nagpur Agri Store',
    retailerType: 'Oil Seeds & Grocery',
    retailerLocation: 'Nagpur City',
    retailerCost: 5200,
    consumerPrice: 5800,
    retailerMarket: 'Local & Urban Consumer Market',
    transportCost: 190,
    distance: 190,
  },
];

export const mockGovernmentUpdates = [
  {
    id: 1,
    category: 'Market notice',
    title: 'Mandi Holiday Alerts',
    description: 'Patiala Mandi will remain closed on 15 August for Independence Day. Plan produce deliveries for the next working day.',
    icon: '📢',
  },
  {
    id: 2,
    category: 'Local support',
    title: 'Block Officer Contact',
    description: 'For crop advisories and field support, contact the Patiala Block Agriculture Office on working days between 9 AM and 5 PM.',
    icon: '☎️',
  },
  {
    id: 3,
    category: 'Scheme update',
    title: 'Active Government Schemes',
    description: 'Applications are open for PM-KISAN support, crop insurance, and farm mechanisation assistance. Check eligibility before applying.',
    icon: '🏛️',
  },
];

export const mockMandis = [
  { id: 1, name: 'Chandauli Mandi', district: 'Chandauli', latitude: 25.2638, longitude: 83.2647, state: 'Uttar Pradesh' },
  { id: 2, name: 'Mughalsarai Mandi', district: 'Chandauli', latitude: 25.2776, longitude: 83.1149, state: 'Uttar Pradesh' },
  { id: 3, name: 'Varanasi Mandi', district: 'Varanasi', latitude: 25.3176, longitude: 82.9739, state: 'Uttar Pradesh' },
  { id: 4, name: 'Ghazipur Mandi', district: 'Ghazipur', latitude: 25.5786, longitude: 83.5782, state: 'Uttar Pradesh' },
  { id: 5, name: 'Mirzapur Mandi', district: 'Mirzapur', latitude: 25.1450, longitude: 82.5684, state: 'Uttar Pradesh' },
  { id: 6, name: 'Chakia Mandi', district: 'Chandauli', latitude: 25.0475, longitude: 83.2706, state: 'Uttar Pradesh' },
  { id: 7, name: 'Bhopal Mandi', district: 'Bhopal', latitude: 23.2599, longitude: 77.4126, state: 'Madhya Pradesh' },
  { id: 8, name: 'Indore Mandi', district: 'Indore', latitude: 22.7196, longitude: 75.8577, state: 'Madhya Pradesh' },
  { id: 9, name: 'Ludhiana Mandi', district: 'Ludhiana', latitude: 30.9010, longitude: 75.8573, state: 'Punjab' },
  { id: 10, name: 'Karnal Mandi', district: 'Karnal', latitude: 29.6857, longitude: 76.9905, state: 'Haryana' },
  { id: 11, name: 'Jaipur Mandi', district: 'Jaipur', latitude: 26.9124, longitude: 75.7873, state: 'Rajasthan' },
  { id: 12, name: 'Nashik Mandi', district: 'Nashik', latitude: 19.9975, longitude: 73.7898, state: 'Maharashtra' }
];

